echo "";echo ""
echo "Now your IAAS should be set and ready to use bbl to create a bosh environment."
echo ""; echo "What you should do now:"
echo "# The following will enable the bbl command by sourcing the required env vars"
echo "source $BBL_ENVIRONMENT_VARS"
echo "bbl -h						# familiarize yourself with bbl generally"
echo "bbl plan -h					# familiarize yourself with the bbl plan command line options"
echo "bbl up -h					# familiarize yourself with the bbl up command line options"
echo "bbl plan --lb-type concourse --debug		# this will create lots of structures in \$BBL_STATE_DIRECTORY"
echo "";echo "# after executing bbl plan, now you can go into \$BBL_STATE_DIRECTORY and make edits and customizations"
echo "";echo "bbl up --lb-type concourse --debug		# this will execute the plan with customizations on your IAAS"

echo "";echo ""
echo "In the future, after you bbl up a new environment, you should have a functional BOSH environment"
echo "including a jumpbox and credhub."
echo "";echo "What you should do then:"
echo "In case you lose your environment variables, execute these commands to get them back"
echo "source $BBL_ENVIRONMENT_VARS"
echo "export \$BBL_STATE_DIRECTORY=$BBL_STATE_DIRECTORY"
echo "eval \"\$(bbl print-env)\"				# this will enable the bosh command with required env vars"
echo ""
echo "bosh alias-env \$BBL_IAAS-\$BBL_ENV_NAME		# this will create a bosh environment alias for future use"
echo "bosh -e \$BBL_IAAS-\$BBL_ENV_NAME log-in		# this will test your login ability to this bosh environment"
echo "bbl ssh --jumpbox				# this is how to ssh into the jumpbox in your bosh environment"
echo "bbl ssh --director				# this is how to ssh into the bosh director"
echo ""; echo "The following is how to create an SSH tunnel through the jumpbox to credhub"
echo "bbl ssh-key > /tmp/jumpbox.key"
echo "chmod 0700 /tmp/jumpbox.key"
echo "ssh -4 -D 5000 -fNC jumpbox@\`bbl jumpbox-address\` -i /tmp/jumpbox.key"
echo "export http_proxy=socks5://localhost:5000"
echo "credhub login"
echo "credhub find -n \'cf_admin_password\'		# you might not have cf installed in this example query"
echo "";echo""
echo "Don't forget to upload stemcells suitable for any deployments you're considering."
echo "The list of available stemcells is here:  https://bosh.cloudfoundry.org/stemcells/"
echo "Uploading stemcells looks like the following:"
echo "Latest version for GCP (may not be supported by your deployment)"
echo "bosh upload-stemcell --sha1 7fec9feec30ce85784b8c0a2de465379a5882e8f \\"
echo "	  https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-trusty-go_agent?v=3586.27"
echo "";echo "Latest version for Azure (may not be supported by your deployment)"
echo "bosh upload-stemcell --sha1 c32675c378994b86c7122a79466074e7a0bac434 \\"
echo "	  https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent?v=3586.27"
echo "";echo "Latest version for AWS (may not be supported by your deployment)"
echo "bosh upload-stemcell --sha1 e1ab7bd57784cfcc790c41765aaad2b50b41bd8b \\"
echo "	  https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3586.27"
echo "";echo "# Thanks for using bblwrap.sh!"

